version: 1.0.{build}
image: Visual Studio 2019 Preview
before_build:
- cmd: >-
    cd .\src\synthesizer

    nuget restore
build:
  project: C:\projects\synthesizer\src\synthesizer\synthesizer.sln
  verbosity: minimal
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false